version: "3.7"

services:
  ui:
    build: ./ui/docker
    image: kjtully/garagesale/ui
    labels:
      desciption: "GarageSale UI"
    environment:
      SERVER_PORT: "8080"
      ITEM_API_URL: "item-api"
      ITEM_API_PORT: "8081"
      APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: "78df80d5-f501-4f94-bafd-d04c78b057be"
      APPDYNAMICS_AGENT_ACCOUNT_NAME: "customer1"
      APPDYNAMICS_CONTROLLER_HOST_NAME: "192.168.86.40"
      APPDYNAMICS_CONTROLLER_PORT: "8090"
      APPDYNAMICS_CONTROLLER_SSL_ENABLED: "false"
      APPDYNAMICS_AGENT_APPLICATION_NAME: "GarageSale-Compose"
      APPDYNAMICS_AGENT_TIER_NAME: "UI"
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME: "true"
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX: "ui-container"
      #PATH: "/usr/local/openjdk-8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/openjdk-8/lib"
      # MacOS - uncomment the NETVIZ env vars to use local docker-compose network
      APPDYNAMICS_NETVIZ_AGENT_HOST: "appd-netviz"
      APPDYNAMICS_NETVIZ_AGENT_PORT: "3892"
      APPDYNAMICS_BROWSER_EUM_APPKEY: "AD-AAB-AAX-JUF"
      APPDYNAMICS_BROWSER_EUM_ADRUM_EXT_URL_HTTP: "http://cdn.appdynamics.com"
      APPDYNAMICS_BROWSER_EUM_ADRUM_EXT_URL_HTTPS: "https://cdn.appdynamics.com"
      APPDYNAMICS_BROWSER_EUM_BEACON_HTTP: "http://col.eum-appdynamics.com"
      APPDYNAMICS_BROWSER_EUM_BEACON_HTTPS: "https://col.eum-appdynamics.com"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '2'
          #NanoCpus: '750000000'
          memory: 512M
        reservations:
          cpus: '1'
          #NanoCPUs: '250000000'
          memory: 256M
    #entrypoint: ["java", "-javaagent:/opt/appdynamics/java/javaagent.jar", "-jar", "spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar"]

  item-api:
    build: ./item-api/docker
    image: kjtully/garagesale/item-api
    labels:
      desciption: "GarageSale Item API"
    environment:
      SERVER_PORT: "8081"
      APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: "78df80d5-f501-4f94-bafd-d04c78b057be"
      APPDYNAMICS_AGENT_ACCOUNT_NAME: "customer1"
      APPDYNAMICS_CONTROLLER_HOST_NAME: "192.168.86.40"
      APPDYNAMICS_CONTROLLER_PORT: "8090"
      APPDYNAMICS_CONTROLLER_SSL_ENABLED: "false"
      APPDYNAMICS_AGENT_APPLICATION_NAME: "GarageSale-Compose"
      APPDYNAMICS_AGENT_TIER_NAME: "Item-API"
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME: "true"
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX: "item-api-container"
      # MacOS - uncomment the NETVIZ env vars to use local docker-compose network
      APPDYNAMICS_NETVIZ_AGENT_HOST: "appd-netviz"
      APPDYNAMICS_NETVIZ_AGENT_PORT: "3892"
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          cpus: '2'
          #NanoCpus: '750000000'
          memory: 512M
        reservations:
          cpus: '1'
          #NanoCPUs: '250000000'
          memory: 256M
    #entrypoint: ["java", "-javaagent:/opt/appdynamics/java/javaagent.jar", "-jar", "spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar"]

  appd-machine:
    image: appdynamics/machine-agent-analytics:latest
    environment:
      APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: "78df80d5-f501-4f94-bafd-d04c78b057be"
      APPDYNAMICS_AGENT_ACCOUNT_NAME: "customer1"
      APPDYNAMICS_CONTROLLER_HOST_NAME: "192.168.86.40"
      APPDYNAMICS_CONTROLLER_PORT: "8090"
      APPDYNAMICS_CONTROLLER_SSL_ENABLED: "false"
      #MACHINE_AGENT_PROPERTIES: "-Dappdynamics.sim.enabled=true -Dappdynamics.docker.enabled=true"
      APPDYNAMICS_SIM_ENABLED: "true"
      APPDYNAMICS_DOCKER_ENABLED: "true"
      APPDYNAMICS_AGENT_ENABLE_CONTAINERIDASHOSTID: "true"
      EVENT_ENDPOINT: "http://192.168.86.40:9080"
      APPDYNAMICS_AGENT_GLOBAL_ACCOUNT_NAME: "customer1_c60204f2-f8c9-40f9-9155-162a513b7900"
      APPDYNAMICS_AGENT_UNIQUE_HOST_ID: "GarageSaleMaContainer"
    volumes:
      - /proc:/hostroot/proc:ro
      - /sys:/hostroot/sys:ro
      - /etc:/hostroot/etc:ro
      - /var/run/docker.sock:/var/run/docker.sock

  appd-netviz:
    image: appdynamics/machine-agent-netviz:latest
    # MacOS, comment out "host" network_mode
    #network_mode: "host"
    #restart: unless-stopped
    ports:
      - "3892:3892"
    cap_add:
      - ALL
      #- NET_ADMIN
      #- NET_RAW

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14250:14250"
