version: "3.2"

services:
  ui:
    #build: ./ui/docker
    image: kjtully/garagesale-ui:20.10
    labels:
      desciption: "GarageSale UI"
    environment:
      SERVER_PORT: "8080"
      ITEM_API_URL: "$ITEM_API_URL"
      ITEM_API_PORT: "$ITEM_API_PORT"
      APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: "$APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY"
      APPDYNAMICS_AGENT_ACCOUNT_NAME: "$APPDYNAMICS_AGENT_ACCOUNT_NAME"
      APPDYNAMICS_CONTROLLER_HOST_NAME: "$APPDYNAMICS_CONTROLLER_HOST_NAME"
      APPDYNAMICS_CONTROLLER_PORT: "$APPDYNAMICS_CONTROLLER_PORT"
      APPDYNAMICS_CONTROLLER_SSL_ENABLED: "$APPDYNAMICS_CONTROLLER_SSL_ENABLED"
      APPDYNAMICS_AGENT_APPLICATION_NAME: "$APPDYNAMICS_AGENT_APPLICATION_NAME"
      APPDYNAMICS_AGENT_TIER_NAME: "UI"
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME: "true"
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX: "ui-container"
      # MacOS - uncomment the NETVIZ env vars to use local docker-compose network
      #APPDYNAMICS_NETVIZ_AGENT_HOST: "$APPDYNAMICS_NETVIZ_AGENT_HOST"
      #APPDYNAMICS_NETVIZ_AGENT_PORT: "$APPDYNAMICS_NETVIZ_AGENT_PORT"
      APPDYNAMICS_BROWSER_EUM_APPKEY: "$APPDYNAMICS_BROWSER_EUM_APPKEY"
      APPDYNAMICS_BROWSER_EUM_ADRUM_EXT_URL_HTTP: "$APPDYNAMICS_BROWSER_EUM_ADRUM_EXT_URL_HTTP"
      APPDYNAMICS_BROWSER_EUM_ADRUM_EXT_URL_HTTPS: "$APPDYNAMICS_BROWSER_EUM_ADRUM_EXT_URL_HTTPS"
      APPDYNAMICS_BROWSER_EUM_BEACON_HTTP: "$APPDYNAMICS_BROWSER_EUM_BEACON_HTTP"
      APPDYNAMICS_BROWSER_EUM_BEACON_HTTPS: "$APPDYNAMICS_BROWSER_EUM_BEACON_HTTPS"
      # Docker Hostname to pre-populate Jaeger link in UI
      DOCKER_HOSTNAME: "$DOCKER_HOSTNAME"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '2'
          #NanoCpus: '750000000'
          memory: 512M
        reservations:
          cpus: '1'
          #NanoCPUs: '250000000'
          memory: 256M

  item-api:
    #build: ./item-api/docker
    image: kjtully/garagesale-item-api:20.10
    labels:
      desciption: "GarageSale Item API"
    environment:
      SERVER_PORT: "8081"
      APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: "$APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY"
      APPDYNAMICS_AGENT_ACCOUNT_NAME: "$APPDYNAMICS_AGENT_ACCOUNT_NAME"
      APPDYNAMICS_CONTROLLER_HOST_NAME: "$APPDYNAMICS_CONTROLLER_HOST_NAME"
      APPDYNAMICS_CONTROLLER_PORT: "$APPDYNAMICS_CONTROLLER_PORT"
      APPDYNAMICS_CONTROLLER_SSL_ENABLED: "$APPDYNAMICS_CONTROLLER_SSL_ENABLED"
      APPDYNAMICS_AGENT_APPLICATION_NAME: "$APPDYNAMICS_AGENT_APPLICATION_NAME"
      APPDYNAMICS_AGENT_TIER_NAME: "Item-API"
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME: "true"
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX: "item-api-container"
      # MacOS - uncomment the NETVIZ env vars to use local docker-compose network
      #APPDYNAMICS_NETVIZ_AGENT_HOST: "$APPDYNAMICS_NETVIZ_AGENT_HOST"
      #APPDYNAMICS_NETVIZ_AGENT_PORT: "$APPDYNAMICS_NETVIZ_AGENT_PORT"
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          cpus: '2'
          #NanoCpus: '750000000'
          memory: 512M
        reservations:
          cpus: '1'
          #NanoCPUs: '250000000'
          memory: 256M

  appd-machine:
    image: appdynamics/machine-agent-analytics:latest
    environment:
      APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: "$APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY"
      APPDYNAMICS_AGENT_ACCOUNT_NAME: "$APPDYNAMICS_AGENT_ACCOUNT_NAME"
      APPDYNAMICS_CONTROLLER_HOST_NAME: "$APPDYNAMICS_CONTROLLER_HOST_NAME"
      APPDYNAMICS_CONTROLLER_PORT: "$APPDYNAMICS_CONTROLLER_PORT"
      APPDYNAMICS_CONTROLLER_SSL_ENABLED: "$APPDYNAMICS_CONTROLLER_SSL_ENABLED"
      APPDYNAMICS_SIM_ENABLED: "$APPDYNAMICS_SIM_ENABLED"
      APPDYNAMICS_DOCKER_ENABLED: "$APPDYNAMICS_DOCKER_ENABLED"
      APPDYNAMICS_AGENT_ENABLE_CONTAINERIDASHOSTID: "$APPDYNAMICS_AGENT_ENABLE_CONTAINERIDASHOSTID"
      #EVENT_ENDPOINT: "$EVENT_ENDPOINT"
      #APPDYNAMICS_AGENT_GLOBAL_ACCOUNT_NAME: "$APPDYNAMICS_AGENT_GLOBAL_ACCOUNT_NAME"
      APPDYNAMICS_AGENT_UNIQUE_HOST_ID: "$APPDYNAMICS_AGENT_UNIQUE_HOST_ID"
    volumes:
      - /proc:/hostroot/proc:ro
      - /sys:/hostroot/sys:ro
      - /etc:/hostroot/etc:ro
      - /var/run/docker.sock:/var/run/docker.sock

  appd-netviz:
    image: appdynamics/machine-agent-netviz:latest
    network_mode: "host"
    ports:
      - "3892:3892"
    cap_add:
      - NET_ADMIN
      - NET_RAW

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14250:14250"
