apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-api
  labels:
    app: item-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item-api
  template:
    metadata:
      labels:
        app: item-api
    spec:
      containers:
      - name: ui
        image: kjtully/garagesale-item-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: SERVER_PORT
          value: '8081'
        - name: APPDYNAMICS_CONTROLLER_HOST_NAME
          value: '$APPDYNAMICS_CONTROLLER_HOST_NAME'
        - name: APPDYNAMICS_CONTROLLER_PORT
          value: '$APPDYNAMICS_CONTROLLER_PORT'
        - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
          value: '$APPDYNAMICS_CONTROLLER_SSL_ENABLED'
        - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
          value: '$APPDYNAMICS_AGENT_ACCOUNT_NAME'
        - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
          value: '$APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY'
        - name: APPDYNAMICS_AGENT_APPLICATION_NAME
          value: GarageSale-K8s
        - name: APPDYNAMICS_AGENT_TIER_NAME
          value: item-api
        - name: APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME
          value: 'true'
        - name: APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX
          value: 'item-api'
        - name: APPDYNAMICS_NETVIZ_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: APPDYNAMICS_NETVIZ_AGENT_PORT
          value: '3892'
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: item-api
  labels:
    app: item-api
spec:
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: item-api
  type: NodePort
