apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: kjtully/garagesale-ui:20.6
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: '8080'
        - name: ITEM_API_URL
          value: 'item-api'
        - name: ITEM_API_PORT
          value: '8081'
        - name: APPDYNAMICS_CONTROLLER_HOST_NAME
          value: '192.168.86.40'
        - name: APPDYNAMICS_CONTROLLER_PORT
          value: '8090'
        - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
          value: 'false'
        - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
          value: 'customer1'
        - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
          value: '78df80d5-f501-4f94-bafd-d04c78b057be'
        - name: APPDYNAMICS_AGENT_APPLICATION_NAME
          value: GarageSale-K8s
        - name: APPDYNAMICS_AGENT_TIER_NAME
          value: ui
        - name: APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME
          value: 'true'
        - name: APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX
          value: 'ui'
        - name: APPDYNAMICS_BROWSER_EUM_APPKEY
          value: 'AD-AAB-AAX-JUF'
        - name: APPDYNAMICS_BROWSER_EUM_ADRUM_EXT_URL_HTTP
          value: 'http://cdn.appdynamics.com'
        - name: APPDYNAMICS_BROWSER_EUM_ADRUM_EXT_URL_HTTPS
          value: 'https://cdn.appdynamics.com'
        - name: APPDYNAMICS_BROWSER_EUM_BEACON_HTTP
          value: 'http://col.eum-appdynamics.com'
        - name: APPDYNAMICS_BROWSER_EUM_BEACON_HTTPS
          value: 'https://col.eum-appdynamics.com'
        - name: APPDYNAMICS_NETVIZ_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: APPDYNAMICS_NETVIZ_AGENT_PORT
          value: '3892'
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: ui
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: ui
  type: NodePort
